var arr1=[
'involved',
 'considering',
 'perception', 
 'suppose',
 'complain',
 'constantly',
'compassionate',
'exquisite',
 'coincide',
 'subtle',
 'long-term',
 'couple',
 'decade',
 'annual',
 'ripe',
 'caution',
'override',
 'generally',
 'delay',
 'delayed',
 'originally',
'blame',
 'revealing', 
 'revealed', 
 'modest',
 'thrusters',
 'eliminated', 
'slump', 
'dropped',
 'sobering', 
 'livelihoods', 
 'shortage', 
'outnumber', 
'misaligned',
 'inevitable',
 'disappointment', 
 'unreliable',
 'acceleration',
 'pledge',
 'strive',
 'accelerate',
 'hesitation', 
 'fight/battle', 
 'importance', 
 'disagreements', 
 'challenge',
 'resolution', 
 'split',
 'evolving/developing',
 'struck out',
 'fascinate', 
 'tempting', 
 'peacefully', 
 'violence',
 'far from peaceful',
 'rivalled',
 'Neanderthals', 
 'atop the food chain',
 'rival', 
 'strikingly', 
 'implies',
 'common',
 'inherited', 
 'intrinsic', 
 'ancient', 
 'reveals', 
 'remarkably',
 'shrines',
 'defies',
 'hesitated'

 
];
var arr2=[
'вовлеченный',
'учитывая',
'восприятие',
'предполагать', 
'жаловаться',
'постоянно',
'состродательный',
'изысканный',
'совпадать',
 'тонкий', 
 'долгосрочный', 
 'пара', 
 'десятилетие', 
 'годовой',
 'зрелый, спелый',
 'осторожность',
'отменять', 
'в целом, обычно',
 'задержка', 
 'отложенный', 
 'первоначально',
'вина', 
 'выявление', 
'выявленный', 
'скромный', 
'двигатели', 
'устранен', 
'спад',
 'упал', 
 'отрезвляющий',
 'средства к существованию',
 'нехватка', 
'превосходить численностью', 
'разрегулированный', 
'неизбежный', 
'разочарование',
 'ненадежна', 
 'ускорение',
'залог', 
'бороться', 
'ускорять', 
'нерешительность', 
'борьба',
 'важность', 
 'разногласия', 
 'проблема', 
'разрешение', 
'раскол',
 'развивающийся', 
 'направляться,</br>вычеркнуть', 
 'очаровывать', 
 'заманчивый', 
 'мирно', 
 'жестокость',
'далеко не мирный',
 'соперничал', 
 'Неандертальцы', 
 'на вершине пищевой </br>цепи', 
 'соперник',
 'поразительно', 
 'подразумевает',
'общий,</br>распространенный', 
'унаследованный', 
'собственный',
 'древний',
 'раскрывать', 
 'необыкновенно', 
 'святыни',
'бросает вызов',
 'колебался'

];
